Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
beat raised exception <class 'django.db.utils.OperationalError'>: OperationalError(2003, "Can't connect to MySQL server on '192.168.2.101' (timed out)")
Traceback (most recent call last):
  File "/home/django/cso_venv/lib64/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 582, in connect
    **kwargs)
  File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.101' (timed out)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/apps/beat.py", line 107, in start_scheduler
    service.start()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 549, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/home/django/cso_venv/lib64/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 593, in scheduler
    return self.get_scheduler()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 588, in get_scheduler
    lazy=lazy,
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 221, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 206, in __init__
    self.setup_schedule()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 229, in setup_schedule
    self.install_default_entries(self.schedule)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 350, in schedule
    self._schedule = self.all_as_schedule()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 235, in all_as_schedule
    for model in self.Model.objects.enabled():
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
    self.connect()
  File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 629, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on '192.168.2.101' (timed out)")
Traceback (most recent call last):
File "/home/django/cso_venv/lib64/python3.6/site-packages/kombu/utils/objects.py", line 42, in __get__
return obj.__dict__[self.__name__]
KeyError
:
'scheduler'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 582, in connect
**kwargs)
File "/usr/lib64/python3.6/socket.py", line 724, in create_connection
raise err
File "/usr/lib64/python3.6/socket.py", line 713, in create_connection
sock.connect(sa)
socket
.
timeout
:
timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
self.connect()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
self.connection = self.get_new_connection(conn_params)
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
return Database.connect(**conn_params)
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
return Connection(*args, **kwargs)
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
self.connect()
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 629, in connect
raise exc
pymysql.err
.
OperationalError
:
(2003, "Can't connect to MySQL server on '192.168.2.101' (timed out)")
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/django/xx-scan/../cso_venv/bin/celery", line 11, in <module>
sys.exit(main())
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/__main__.py", line 14, in main
_main()
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/celery.py", line 326, in main
cmd.execute_from_commandline(argv)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
super(CeleryCommand, self).execute_from_commandline(argv)))
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
return self.handle_argv(self.prog_name, argv[1:])
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
return self.execute(command, argv)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
).run_from_argv(self.prog_name, argv[1:], command=argv[0])
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/base.py", line 285, in run_from_argv
sys.argv if argv is None else argv, command)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/base.py", line 368, in handle_argv
return self(*args, **options)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
ret = self.run(*args, **kwargs)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/bin/beat.py", line 105, in run
return beat().run()
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/apps/beat.py", line 79, in run
self.start_scheduler()
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/apps/beat.py", line 107, in start_scheduler
service.start()
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 549, in start
humanize_seconds(self.scheduler.max_interval))
File "/home/django/cso_venv/lib64/python3.6/site-packages/kombu/utils/objects.py", line 44, in __get__
value = obj.__dict__[self.__name__] = self.__get(obj)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 593, in scheduler
return self.get_scheduler()
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 588, in get_scheduler
lazy=lazy,
File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 221, in __init__
Scheduler.__init__(self, *args, **kwargs)
File "/home/django/cso_venv/lib64/python3.6/site-packages/celery/beat.py", line 206, in __init__
self.setup_schedule()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 229, in setup_schedule
self.install_default_entries(self.schedule)
File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 350, in schedule
self._schedule = self.all_as_schedule()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django_celery_beat/schedulers.py", line 235, in all_as_schedule
for model in self.Model.objects.enabled():
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 268, in __iter__
self._fetch_all()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
self._result_cache = list(self._iterable_class(self))
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
cursor = self.connection.cursor()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
return self._cursor()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
self.ensure_connection()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
self.connect()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
self.connect()
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
self.connection = self.get_new_connection(conn_params)
File "/home/django/cso_venv/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
return Database.connect(**conn_params)
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/__init__.py", line 94, in Connect
return Connection(*args, **kwargs)
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 327, in __init__
self.connect()
File "/home/django/cso_venv/lib64/python3.6/site-packages/pymysql/connections.py", line 629, in connect
raise exc
django.db.utils
.
OperationalError
:
(2003, "Can't connect to MySQL server on '192.168.2.101' (timed out)")
Writing entries...
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:

beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
Writing entries...
Writing entries...
Writing entries...
Writing entries...
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:
<ModelEntry: celery.backend_cleanup celery.backend_cleanup(*[], **{}) <crontab: 0 4
         * *
          * (m/h/d/dM/MY), UTC>
        >
beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
Setting default socket timeout to 30
beat: Starting...
DatabaseScheduler: initial read
Writing entries...
DatabaseScheduler: Fetching database schedule
Current schedule:

beat: Ticking with max interval->1.00 minute
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Synchronizing schedule...
Writing entries...
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
beat: Waking up in 1.00 minute.
